name: Android Build Action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch from which we have to build'
        required: true

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

jobs:
  build:
    name: Setup environment and build
    runs-on: self-hosted
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Lint check
        run: ./gradlew ktlintCheck

      - name: Unit and UI tests with Jacoco
        run: ./gradlew jacocoTestReport

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/jacoco/jacocoTestReport

      - name: Download test reports
        uses: actions/download-artifact@v2
        with:
          name: report
          path: app/build/reports/jacoco/jacocoTestReport

      - name: Export test report
        uses: codecov/codecov-action@v3
        with:
          files: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

      - name: Build debug
        run: ./gradlew assembleDebug
